// flow-typed signature: e452b9b1360f63d9074c4e0015416d61
// flow-typed version: <<STUB>>/args_v2.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'args'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'args' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'args/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'args/dist/index.js' {
  declare module.exports: $Exports<'args/dist/index'>;
}
