// flow-typed signature: 8a6ff50bb5c64f2a2fd6b14dd9c2003e
// flow-typed version: <<STUB>>/find-package-json_v^1.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'find-package-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'find-package-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'find-package-json/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'find-package-json/index' {
  declare module.exports: $Exports<'find-package-json'>;
}
declare module 'find-package-json/index.js' {
  declare module.exports: $Exports<'find-package-json'>;
}
declare module 'find-package-json/test.js' {
  declare module.exports: $Exports<'find-package-json/test'>;
}
